title: ğŸ†‚ğŸ…¸ğŸ…³ğŸ…³ğŸ…·ğŸ…°ğŸ†ğŸ†ƒğŸ…·'ğŸ†‚ ğŸ…±ğŸ…»ğŸ…¾ğŸ…¶
description:
google_analytics:
show_downloads: false
#theme: jekyll-theme-dinky
remote_theme:  mmistakes/jekyll-theme-basically-basic

exclude: [ archive ]

lang: en-US

github_username: gitSiddharth
email: jsiddharth80@gmail.com

name: Siddharth J 

plugins:
  - jekyll-mentions
  - jekyll-remote-theme
